# Generated by Django 3.2 on 2021-05-03 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0006_alter_empresa_user_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('cd_participante', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('participante', models.CharField(blank=True, max_length=130, verbose_name='Nome do participante')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='participantes/%d/%m/%Y/')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa Relacionada')),
            ],
        ),
    ]
