# Generated by Django 2.2.3 on 2019-10-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EneaTipo',
            fields=[
                ('cd_enae_tipo', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('no_enae_tipo', models.CharField(max_length=50, verbose_name='Enae tipo')),
                ('nu_enae_tipo', models.CharField(max_length=1, verbose_name='Nº do Enae Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='PerguntaQuestionario',
            fields=[
                ('cd_per_questionario', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nu_pergunta', models.CharField(max_length=2, verbose_name='Nº Pergunta')),
                ('ds_pergunta', models.CharField(max_length=250, verbose_name='Pergunta')),
                ('res_per_questionarioA', models.CharField(max_length=100, verbose_name='Alternativa (A)')),
                ('val_per_questionarioA', models.IntegerField(choices=[(None, ''), (1, 'PERFECCIONISTA'), (2, 'PRESTATIVO'), (3, 'BEM-SUCEDIDO'), (4, 'ROMÂNTICO'), (5, 'OBSERVADOR'), (6, 'QUESTIONADOR'), (7, 'SONHADOR'), (8, 'CONFRONTADOR'), (9, 'PRESERVACIONISTA')], verbose_name='Tipo Resposta A')),
                ('res_per_questionarioB', models.CharField(max_length=100, verbose_name='Alternativa (B)')),
                ('val_per_questionarioB', models.IntegerField(choices=[(None, ''), (1, 'PERFECCIONISTA'), (2, 'PRESTATIVO'), (3, 'BEM-SUCEDIDO'), (4, 'ROMÂNTICO'), (5, 'OBSERVADOR'), (6, 'QUESTIONADOR'), (7, 'SONHADOR'), (8, 'CONFRONTADOR'), (9, 'PRESERVACIONISTA')], verbose_name='Tipo Resposta b')),
            ],
        ),
    ]
