# Generated by Django 2.2.3 on 2019-10-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_eneatipo_perguntaquestionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicasPersona',
            fields=[
                ('cd_caracteristica', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('no_caracteristica', models.CharField(max_length=100, verbose_name='Caracteristica: ')),
                ('tp_caracteristica', models.IntegerField(choices=[(None, ''), (1, 'PERFECCIONISTA'), (2, 'PRESTATIVO'), (3, 'BEM-SUCEDIDO'), (4, 'ROMÂNTICO'), (5, 'OBSERVADOR'), (6, 'QUESTIONADOR'), (7, 'SONHADOR'), (8, 'CONFRONTADOR'), (9, 'PRESERVACIONISTA')], verbose_name='Tipo da caracteristica: ')),
                ('tp_predominate', models.IntegerField(choices=[(None, ''), (1, 'PADRÃO'), (2, 'PREDOMINANTE')], verbose_name='Caracteristica Predominante? : ')),
            ],
        ),
        migrations.RemoveField(
            model_name='borrowed',
            name='to_who',
        ),
        migrations.RemoveField(
            model_name='borrowed',
            name='what',
        ),
        migrations.DeleteModel(
            name='Belonging',
        ),
        migrations.DeleteModel(
            name='Borrowed',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
