# Generated by Django 2.2.6 on 2020-03-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_auto_20191212_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicaspersona',
            name='cd_caracteristica',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eneatipo',
            name='cd_enae_tipo',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='cd_participante',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='perguntaquestionario',
            name='cd_per_questionario',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
