# Generated by Django 3.2 on 2021-07-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vaga', models.CharField(max_length=250, verbose_name='Nome vaga: ')),
                ('descricao', models.TextField(verbose_name='Descrição da Vaga: ')),
                ('locacao', models.CharField(max_length=150, verbose_name='Locacao da vaga')),
                ('status', models.BooleanField(default=True, verbose_name='Status :')),
            ],
            options={
                'verbose_name': 'Vagas',
                'verbose_name_plural': 'Cadastro de Vagas',
            },
        ),
    ]
