# Generated by Django 3.2 on 2021-07-23 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamentoSelecao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Cargo')),
                ('salario_base', models.CharField(max_length=50, verbose_name='Salario Base')),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Cargos',
                'verbose_name_plural': 'Cadastro de Cargos',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Departemento')),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Cadastro de Departamentos',
            },
        ),
        migrations.AlterField(
            model_name='vagas',
            name='locacao',
            field=models.TextField(verbose_name='Descrição da Vaga: '),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='nome_vaga',
            field=models.TextField(verbose_name='Descrição da Vaga: '),
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabalhe_conosco', models.BooleanField(verbose_name='Padrão do trabalhe Conosco?')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recrutamentoSelecao.cargos', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Questionario',
                'verbose_name_plural': 'Cadastro de Questionario',
            },
        ),
        migrations.CreateModel(
            name='Perguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=256, verbose_name='Pergunta')),
                ('resposta1', models.CharField(blank=True, max_length=256, null=True, verbose_name='resposta 1')),
                ('resposta2', models.CharField(blank=True, max_length=256, null=True, verbose_name='resposta 2')),
                ('resposta3', models.CharField(blank=True, max_length=256, null=True, verbose_name='resposta 5')),
                ('resposta4', models.CharField(blank=True, max_length=256, null=True, verbose_name='resposta 4')),
                ('resposta5', models.CharField(blank=True, max_length=256, null=True, verbose_name='resposta 5')),
                ('questionario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutamentoSelecao.questionario', verbose_name='Questionario')),
            ],
            options={
                'verbose_name': 'Perguntas',
                'verbose_name_plural': 'Perguntas',
            },
        ),
        migrations.AddField(
            model_name='cargos',
            name='departamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recrutamentoSelecao.departamento', verbose_name='Departamento'),
        ),
    ]
