# Generated by Django 3.2 on 2021-08-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamentoSelecao', '0003_auto_20210723_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perguntas',
            options={'verbose_name': 'Perguntas', 'verbose_name_plural': 'Cadastro de Perguntas'},
        ),
    ]
