# Generated by Django 3.2.7 on 2021-10-17 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamentoSelecao', '0004_alter_perguntas_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargos',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutamentoSelecao.departamento'),
        ),
        migrations.AlterField(
            model_name='cargos',
            name='status',
            field=models.BooleanField(verbose_name='Cargo Ativo ?'),
        ),
    ]
