# Generated by Django 3.2.7 on 2022-02-28 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabalheConosco', '0005_alter_dadosprofissionais_descricao'),
        ('recrutamentoSelecao', '0005_auto_20211017_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('id_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabalheConosco.candidato', verbose_name='Candidato')),
            ],
            options={
                'verbose_name': 'Entrevista',
                'verbose_name_plural': 'Entrevista',
            },
        ),
    ]
