# Generated by Django 3.2 on 2021-07-23 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=13, unique=True, verbose_name='Digite seu CPF:')),
                ('email', models.EmailField(max_length=150, verbose_name='Digite seu E-mail:')),
                ('nome', models.CharField(max_length=164, verbose_name='Nome Completo:')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidato',
            },
        ),
        migrations.CreateModel(
            name='QuestionarioPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pergunta', models.CharField(max_length=1, verbose_name='')),
                ('id_resposta', models.CharField(max_length=1, verbose_name='')),
                ('id_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabalheConosco.candidato', verbose_name='Candidato')),
            ],
            options={
                'verbose_name': 'QuestionarioPadrao',
                'verbose_name_plural': 'Questionario ',
            },
        ),
        migrations.CreateModel(
            name='DadosProfissionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo de atuação')),
                ('Empresa', models.CharField(max_length=50, verbose_name='Empresa')),
                ('descricao', models.TextField(verbose_name='descriçao do seu cargo:')),
                ('data_admissao', models.DateField(verbose_name='Data admissao')),
                ('data_demissao', models.DateField(verbose_name='Data Demissao')),
                ('id_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabalheConosco.candidato', verbose_name='Candidato')),
            ],
            options={
                'verbose_name': 'DadosProfisional',
                'verbose_name_plural': 'DadosProfissionais',
            },
        ),
        migrations.CreateModel(
            name='DadosPessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg', models.CharField(max_length=164, verbose_name='RG:')),
                ('sexo', models.CharField(choices=[(None, ''), ('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='SEXO:')),
                ('estado_civil', models.IntegerField(choices=[(None, ''), (1, 'Solteiro'), (2, 'Casado'), (3, 'Separado'), (4, 'Divorciado'), (5, 'Viúvo'), (6, 'Amasiado')], verbose_name='Estado Civil:')),
                ('escolaridade', models.IntegerField(choices=[(None, ''), (1, 'Fundamental - Incompleto'), (2, 'Fundamental - Completo'), (3, 'Médio - Incompleto'), (4, 'Médio - Completo'), (5, 'Superior - Incompleto'), (6, 'Superior - Completo'), (7, 'Pós-graduação (Lato senso) - Incompleto'), (8, 'Pós-graduação (Lato senso) - Completo'), (9, 'Pós-graduação (Stricto sensu, nível mestrado) - Incompleto'), (10, 'Pós-graduação (Stricto sensu, nível mestrado) - Completo'), (11, 'Pós-graduação (Stricto sensu, nível doutor) - Incompleto')], verbose_name='Escolaridade:')),
                ('contato', models.CharField(max_length=12, verbose_name='Numero para contato')),
                ('nome_mae', models.CharField(max_length=164, verbose_name='Nome da Mãe:')),
                ('nome_pai', models.CharField(max_length=164, verbose_name='Nome do Pai:')),
                ('endereco', models.CharField(max_length=256, verbose_name='Endereco:')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade:')),
                ('estado', models.CharField(max_length=35, verbose_name='Estado:')),
                ('id_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabalheConosco.candidato', verbose_name='Candidato')),
            ],
            options={
                'verbose_name': 'DadosPessoas',
                'verbose_name_plural': 'Dados Pessoass',
            },
        ),
        migrations.CreateModel(
            name='DadosEscolaridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Curso/Escola')),
                ('status', models.IntegerField(choices=[(None, ''), (1, 'Incompleto'), (2, 'Completo')], verbose_name='Escolaridade:')),
                ('data_inicio', models.DateField(verbose_name='Data de inicio')),
                ('data_fim', models.DateField(verbose_name='Previsão termino/data termino')),
                ('id_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabalheConosco.candidato', verbose_name='Candidato')),
            ],
            options={
                'verbose_name': 'DadosEscolaridade',
                'verbose_name_plural': 'DadosEscolaridades',
            },
        ),
    ]
