# Generated by Django 3.2 on 2021-08-09 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamentoSelecao', '0004_alter_perguntas_options'),
        ('trabalheConosco', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidato',
            options={'verbose_name': 'Candidato', 'verbose_name_plural': 'Banco de Curriculo'},
        ),
        migrations.CreateModel(
            name='vagasCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabalheConosco.candidato', verbose_name='Candidato')),
                ('id_vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutamentoSelecao.vagas', verbose_name='Vagas Disponivel')),
            ],
            options={
                'verbose_name': 'vagasCandidato',
                'verbose_name_plural': 'Vagas candidato',
            },
        ),
    ]
