# Generated by Django 3.2.7 on 2021-10-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalheConosco', '0004_auto_20211003_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosprofissionais',
            name='descricao',
            field=models.TextField(verbose_name='descriçao de atividade:'),
        ),
    ]
