# Generated by Django 3.2.7 on 2022-02-28 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recrutamentoSelecao', '0006_entrevista'),
        ('trabalheConosco', '0005_alter_dadosprofissionais_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospessoas',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='dadospessoas',
            name='endereco',
            field=models.CharField(max_length=256, verbose_name='Endereco'),
        ),
        migrations.AlterField(
            model_name='dadospessoas',
            name='escolaridade',
            field=models.IntegerField(choices=[(None, ''), (1, 'Fundamental - Incompleto'), (2, 'Fundamental - Completo'), (3, 'Médio - Incompleto'), (4, 'Médio - Completo'), (5, 'Superior - Incompleto'), (6, 'Superior - Completo'), (7, 'Pós-graduação (Lato senso) - Incompleto'), (8, 'Pós-graduação (Lato senso) - Completo'), (9, 'Pós-graduação (Stricto sensu, nível mestrado) - Incompleto'), (10, 'Pós-graduação (Stricto sensu, nível mestrado) - Completo'), (11, 'Pós-graduação (Stricto sensu, nível doutor) - Incompleto')], verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='dadospessoas',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernanbuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='dadospessoas',
            name='estado_civil',
            field=models.IntegerField(choices=[(None, ''), (1, 'Solteiro'), (2, 'Casado'), (3, 'Separado'), (4, 'Divorciado'), (5, 'Viúvo'), (6, 'Amasiado')], verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='dadospessoas',
            name='nome_mae',
            field=models.CharField(max_length=164, verbose_name='Nome da Mãe'),
        ),
        migrations.AlterField(
            model_name='dadospessoas',
            name='nome_pai',
            field=models.CharField(max_length=164, verbose_name='Nome do Pai'),
        ),
        migrations.AlterField(
            model_name='dadospessoas',
            name='sexo',
            field=models.CharField(choices=[(None, ''), ('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='vagascandidato',
            name='id_vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutamentoSelecao.vagas', verbose_name='Vagas em aberto'),
        ),
    ]
