# Generated by Django 3.2 on 2021-04-25 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0002_auto_20210414_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Usuario Vinculados'),
        ),
        migrations.AlterField(
            model_name='solicitacaoreltorio',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa  & Consultor'),
        ),
        migrations.AlterField(
            model_name='solicitacaoreltorio',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Solicitação'),
        ),
        migrations.AlterField(
            model_name='solicitacaoreltorio',
            name='quantidade_restante',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade Restante de Relatorio'),
        ),
        migrations.AlterField(
            model_name='solicitacaoreltorio',
            name='tipo_relatorio',
            field=models.CharField(choices=[(None, ''), ('B', 'BASICO'), ('P', 'PREMIUM')], default=None, max_length=4),
        ),
    ]
