# Generated by Django 3.2 on 2021-04-27 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0003_auto_20210425_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='users',
        ),
        migrations.AddField(
            model_name='empresa',
            name='user_admin',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Administrador'),
        ),
        migrations.CreateModel(
            name='EmpresaUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'EmpresaUsuarios',
                'verbose_name_plural': 'Empresa & Usuarios',
            },
        ),
    ]
