# Generated by Django 3.2 on 2021-04-27 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0004_auto_20210426_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='user_admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Administrador'),
        ),
    ]
