# Generated by Django 3.2 on 2021-04-14 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresa & Consultor'},
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=128, verbose_name='Empresa  & Consultor'),
        ),
        migrations.CreateModel(
            name='SolicitacaoReltorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.IntegerField(verbose_name='Quantidade')),
                ('preco', models.DecimalField(decimal_places=2, editable=False, max_digits=6, verbose_name='Valor da Solicitação')),
                ('quantidade_restante', models.IntegerField(editable=False, verbose_name='Quantidade Restante de Relatorio')),
                ('status', models.BooleanField(default=False, editable=False, verbose_name='Status Solicitação')),
                ('tipo_relatorio', models.CharField(choices=[('B', 'BASICO'), ('P', 'PREMIUM')], default=0, max_length=4)),
                ('data_solicitacao', models.DateField(auto_now=True, null=True, verbose_name='Data Solicitação')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='nome')),
            ],
            options={
                'verbose_name': 'SolicitacaoReltorio',
                'verbose_name_plural': 'Solicitacão de Relatórios',
            },
        ),
    ]
