name: Django CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python ${{ matrix.python-version }}
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #     - name: Install Dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install django-input-mask
  #         pip install gunicorn whitenoise
  #         pip install -r requirements.txt
  #     - name: Run migrations
  #       run: |
  #         python manage.py collectstatic  --noinput
  #         python manage.py makemigrations --noinput
  #         python manage.py migrate --noinput
      # - name: Run Tests
      #   run: |
      #     python manage.py test
      # - name: Check Syntax #We are just testing the syntax in names app; pycodestyle uses pep8 conventions of max line length of 79 characters while Django recommends 119 characters
      #   run: pycodestyle --statistics names
    
  deploy-dev:
    runs-on: ubuntu-latest
    # needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Construir, enviar e liberar um contêiner do Docker para o Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          # O endereço de e-mail associado à sua conta Heroku.
          email: ${{ secrets.HEROKU_EMAIL }}
          # Api Key está disponível nas configurações da sua conta Heroku.
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          # Nome do aplicativo heroku para o qual a compilação deve ser enviada.
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          # (Opcional, padrão: "./")
          # Diretório do Dockerfile.
          dockerfile_directory: ./
          # Nome do Dockerfile.
          dockerfile_name: "Dockerfile"
          # Opções adicionais do comando docker build.
          docker_options: "--no-cache"
          # (Opcional, padrão: "web")
          process_type: web
